name: sar-pipeline
channels:
- conda-forge
- nodefaults
dependencies:
- python >=3.13.7,<3.14
- boto3 >=1.40.30,<2
- click >=8.2.1,<9
- datacube ==1.8.19
- ipykernel >=6.30.1,<7
- odc-stac >=0.4.0,<0.5
- odc-geo >=0.5.0rc1,<0.6
- pip
- pip:
  - -e dataset_prepare_scripts
  - mypy-boto3-s3>=1.40.26, <2
  - pystac-client>=0.9.0, <0.10
  - datacube-ows>=1.8.43, <2
